#
# This is free software, lisence use MIT.
# 
# 
# <https://github.com/Chikage0o0/openwrt-packages>
#

name: Compile-Ipk
on:
  repository_dispatch:
    types: [Compile-IPK]
  workflow_dispatch:

env:
  REMOTE_PATH: drive:Public/Openwrt/Package
  VERSION: 21.02.2
  
jobs:
  compile-ipk:
    runs-on: Ubuntu-20.04

    strategy: 
      fail-fast: false   
      matrix:
        include:
         - target: x86-64
           target_path: x86_64
         - target: ramips-mt7621
           target_path: mipsel_24kc

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: 配置RCLONE
      uses: NiceLabs/rclone-action@master
      with:
        github-token: ${{ secrets.SECRET_TOKEN }}
        config: ${{ secrets.RCLONE_CONFIG }}
        config-secret-name: RCLONE_CONFIG


    - name: 准备环境
      run: |
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
        mkdir -p /workdir/bin/ $$ mkdir -p /workdir/error/
        rclone copy $REMOTE_PATH/${{matrix.target_path}} /workdir/bin/packages/${{matrix.target_path}}/custom/ || true
  
    - name: 编译
      id: compile
      run: |
        docker run --rm -v /workdir/bin/:/home/build/openwrt/bin/  \
            -v $GITHUB_WORKSPACE:/home/build/custom-feed/ \
            -v $GITHUB_WORKSPACE/patch/${{matrix.target}}.config:/home/build/openwrt/custom.config \
            -v /workdir/error/:/home/build/openwrt/error/  \
             openwrtorg/sdk:${{matrix.target}}-$VERSION /bin/bash /home/build/custom-feed/patch/build.sh

        echo "::set-output name=error::`ls -A /workdir/error/`"

    - name: 如果出现失败发送通知
      if: ${{ steps.compile.outputs.error }} != ""
      uses: actions/upload-artifact@v3
      with:
        name: ${{matrix.target}}-error
        path: /workdir/error/
        
    - name: 上传至目标存储
      run: |
        rclone delete $REMOTE_PATH/${{matrix.target_path}}/ || true
        rclone copy /workdir/bin/packages/${{matrix.target_path}}/custom/ $REMOTE_PATH/${{matrix.target_path}}/
    
