#
# This is free software, lisence use MIT.
# 
# 
# <https://github.com/Chikage0o0/openwrt-packages>
#

name: Compile-Ipk
on:
  repository_dispatch:
    types: [Compile-IPK]
  workflow_dispatch:

env:
  VERSION: 21.02.2

jobs:
  compile-ipk:
    runs-on: Ubuntu-20.04

    strategy:    
      matrix:
        target: [x86-64, ramips-mt7621]

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: 配置RCLONE
      uses: NiceLabs/rclone-action@master
      with:
        github-token: ${{ secrets.SECRET_TOKEN }}
        config: ${{ secrets.RCLONE_CONFIG }}
        config-secret-name: RCLONE_CONFIG


    - name: 准备环境
      run: |
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
        mkdir -p /workdir/bin/ $$ mkdir -p /workdir/error/
        rclone copy $REMOTE_PATH/${{matrix.target}}/ /workdir/bin/packages/${{matrix.target}}/custom/ || true
  
    - name: 编译
      run: |
        docker run --rm -v /workdir/bin/:/home/build/openwrt/bin/  \
            -v $GITHUB_WORKSPACE:/home/build/custom-feed/ \
            -v $GITHUB_WORKSPACE/patch/${{matrix.target}}.config:/home/build/openwrt/custom.config \
            -v /workdir/error/:/home/build/openwrt/error/  \
             openwrtorg/sdk:${{matrix.target}}-$VERSION /bin/bash /home/build/custom-feed/patch/build.sh

    - name: 如果出现失败上传日志到artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{matrix.target}}-error
        path: /workdir/error/
        
    - name: 上传至目标存储
      run: |
        rclone delete $REMOTE_PATH || true
        rclone copy /workdir/bin/packages/${{matrix.target}}/custom/ $REMOTE_PATH/${{matrix.target}}/
    
