#
# This is free software, lisence use MIT.
# 
# 
# <https://github.com/Chikage0o0/openwrt-packages>
#

name: Compile-Ipk
on:
  repository_dispatch:
    types: [Compile-IPK]
  workflow_dispatch:

env:
  REMOTE_PATH: drive:Public/Openwrt/Package
  VERSION: 21.02.2
  USE_TG: false
  
jobs:
  compile-ipk:
    runs-on: Ubuntu-20.04

    strategy: 
      fail-fast: false   
      matrix:
        target: [x86-64,ramips-mt7621]

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: 配置RCLONE
      uses: NiceLabs/rclone-action@master
      with:
        github-token: ${{ secrets.SECRET_TOKEN }}
        config: ${{ secrets.RCLONE_CONFIG }}
        config-secret-name: RCLONE_CONFIG


    - name: 准备环境
      run: |
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
        mkdir -p /workdir/packages/ $$ mkdir -p /workdir/error/
        rclone copy $REMOTE_PATH/${{matrix.target}} /workdir/packages/ || true

    - name: 转储签名
      run: echo "${{ secrets.SECRET_KEY }}" > /workdir/key-build

    - name: 编译
      id: compile
      run: |
        docker run --rm -v /workdir/packages/:/home/build/packages/  \
            -v /workdir/key-build:/home/build/openwrt/key-build  \
            -v $GITHUB_WORKSPACE:/home/build/custom-feed/ \
            -v $GITHUB_WORKSPACE/patch/${{matrix.target}}.config:/home/build/openwrt/custom.config \
            -v /workdir/error/:/home/build/openwrt/error/  \
             openwrtorg/sdk:${{matrix.target}}-$VERSION /bin/bash /home/build/custom-feed/patch/build.sh

        if [`ls -A /workdir/error/` == ""] ;then
          echo "compile_error=false" >> $GITHUB_ENV
        else
          echo "compile_error=true" >> $GITHUB_ENV
        fi
        sudo chown $USER:$GROUPS /workdir
        sudo chown $USER:$GROUPS $GITHUB_WORKSPACE

    - name: 如果出现失败上传Artifact
      if: env.compile_error == 'true'
      uses: actions/upload-artifact@v3
      with:
        name: ${{matrix.target}}-error
        path: /workdir/error/
    
    - name: 如果出现失败通知TG
      if: env.compile_error == 'true' && env.USE_TG == 'true'
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: some errors in compile
        
    - name: 上传至目标存储
      run: |
        rclone delete $REMOTE_PATH/${{matrix.target}}/ || true
        rclone copy /workdir/packages/ $REMOTE_PATH/${{matrix.target}}/
    
