#
# This is free software, lisence use MIT.
# 
# 
# <https://github.com/Chikage0o0/openwrt-packages>
#

name: Compile-x86-64
on:
  push:
    paths-ignore:
      - '.github/workflows/**'
      - '.gitignore'
      - 'README.md'
  workflow_dispatch:

env:
  DIFF_CONFIG_FILE: patch/x86-64.config
  REMOTE_PATH: drive:Public/Openwrt/Package/x86_64/
  LOCAL_PATH: /workdir/bin/packages/x86_64/custom/
  TARGET: x86_64
  VERSION: 21.02.2

jobs:
  compile-x86:
    runs-on: Ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: 配置RCLONE
      uses: NiceLabs/rclone-action@master
      with:
        github-token: ${{ secrets.SECRET_TOKEN }}
        config: ${{ secrets.RCLONE_CONFIG }}
        config-secret-name: RCLONE_CONFIG


    - name: 准备环境
      run: |
        USER=`id -u`
        GROUPS=`id -g`
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
        mkdir -p /workdir/bin/ $$ mkdir -p /workdir/error/
        rclone copy $REMOTE_PATH $LOCAL_PATH 
  
    - name: 编译
      run: |
        USER=-`id -u`
        GROUPS=`id -g`
        docker run --rm -v /workdir/bin/:/home/build/openwrt/bin/  \
            -v $GITHUB_WORKSPACE:/home/build/custom-feed/ \
            -v $GITHUB_WORKSPACE/$DIFF_CONFIG_FILE:/home/build/openwrt/custom.config \
            -v /workdir/error/:/home/build/openwrt/error/ -u $USER:$GROUPS \
             openwrtorg/sdk:$TARGET-$VERSION /bin/bash /home/build/custom-feed/patch/build.sh

    - name: 如果出现失败上传日志到artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: /workdir/error/
        
    - name: 上传至目标存储
      run: |
        rclone delete $REMOTE_PATH
        rclone copy $LOCAL_PATH $REMOTE_PATH
    
